In [ ]:
''' Carregando o conjunto de dados '''
import pandas as pd
arquivo = pd.read_csv(r'vinho_machine_learning\wine_dataset.csv')

In [93]:
arquivo.head()

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality,style
0,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red
1,7.8,0.88,0.00,2.6,0.098,25.0,67.0,0.9968,3.20,0.68,9.8,5,red
2,7.8,0.76,0.04,2.3,0.092,15.0,54.0,0.9970,3.26,0.65,9.8,5,red
3,11.2,0.28,0.56,1.9,0.075,17.0,60.0,0.9980,3.16,0.58,9.8,6,red
4,7.4,0.70,0.00,1.9,0.076,11.0,34.0,0.9978,3.51,0.56,9.4,5,red

In [94]:
arquivo['style'] = arquivo['style'].replace('red', 0)

In [95]:
arquivo['style'] = arquivo['style'].replace('white', 1)

In [96]:
''' Separando as variáveis entre preditoras e variável alvo '''
y = arquivo['style'].astype(int)
x = arquivo.drop('style', axis=1)

In [97]:
from sklearn.model_selection import train_test_split

''' Criando os conjuntos de dados de treino e teste '''
x_treino, x_teste, y_treino, y_teste = train_test_split(x, y, test_size = 0.3)

In [98]:
from sklearn.ensemble import ExtraTreesClassifier

''' Criação do modelo '''
modelo = ExtraTreesClassifier()
modelo.fit(x_treino,y_treino)

''' Imprimindo resultado '''
resultado = modelo.score(x_teste, y_teste)
print("Acurácia", resultado)

Acurácia 0.9969230769230769

In [99]:
y_teste[400:403]

2783    1
4299    1
1021    0
Name: style, dtype: int64

In [100]:
x_teste[400:403]

,fixed_acidity,volatile_acidity,citric_acid,residual_sugar,chlorides,free_sulfur_dioxide,total_sulfur_dioxide,density,pH,sulphates,alcohol,quality
2783,7.9,0.46,0.32,4.1,0.033,40.0,138.0,0.99120,3.18,0.44,12.8,7
4299,6.5,0.46,0.31,5.0,0.027,15.0,72.0,0.99165,3.26,0.60,11.5,7
1021,11.3,0.36,0.66,2.4,0.123,3.0,8.0,0.99642,3.20,0.53,11.9,6

In [101]:
previsoes = modelo.predict(x_teste[400:403])

In [102]:
previsoes

array([1, 1, 0])